version: "3.7"

services:
  db:
    container_name: gitla_parse_db
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    container_name: gitlab_parse_backend
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: docker/django/start.sh
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: