# Generated by Django 2.2.2 on 2019-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveIntegerField(unique=True, verbose_name='issue id')),
                ('title', models.TextField(verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('author_name', models.CharField(max_length=100, verbose_name='author name')),
                ('assignee_name', models.CharField(max_length=100, verbose_name='assignee name')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('project_id', models.PositiveIntegerField(unique=True, verbose_name='project_id')),
                ('web_url', models.URLField(verbose_name='web url')),
                ('due_date', models.DateTimeField(verbose_name='dua date')),
                ('time_spent', models.CharField(max_length=50, verbose_name='time spent')),
            ],
            options={
                'verbose_name': ('issue',),
                'verbose_name_plural': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.PositiveIntegerField(verbose_name='repository id')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
            },
        ),
    ]
