# Generated by Django 2.2.2 on 2019-06-22 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('gitlab_username', models.CharField(max_length=200, verbose_name='gitlab username')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.PositiveIntegerField(verbose_name='repository id')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'repository',
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('work_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('author_name', models.CharField(max_length=100, verbose_name='author name')),
                ('assignee_name', models.CharField(max_length=100, verbose_name='assignee name')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
                ('issue_id', models.PositiveIntegerField(verbose_name='issue_id')),
                ('project_id', models.PositiveIntegerField(verbose_name='project_id')),
                ('web_url', models.URLField(verbose_name='web url')),
                ('due_date', models.DateTimeField(verbose_name='dua date')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('time_spend', models.CharField(max_length=50, verbose_name='time spent')),
                ('time_estimate', models.CharField(max_length=50, verbose_name='time estimate')),
            ],
            options={
                'verbose_name': 'work log',
                'verbose_name_plural': 'work logs',
            },
        ),
    ]
