# Generated by Django 2.2.2 on 2019-06-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_parse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='assignee_gitlab_name',
            field=models.CharField(default=12, max_length=100, verbose_name='assignee gitlab username'),
            preserve_default=False,
        ),
    ]
