# Generated by Django 2.2.2 on 2019-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.PositiveIntegerField(verbose_name='project_id'),
        ),
    ]
