# Generated by Django 2.2.2 on 2019-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_parse', '0002_auto_20190618_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.PositiveIntegerField(unique=True, verbose_name='issue id')),
                ('title', models.TextField(verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('author_name', models.CharField(max_length=100, verbose_name='author name')),
                ('assignee_name', models.CharField(max_length=100, verbose_name='assignee name')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
                ('updated_at', models.DateTimeField(verbose_name='updated at')),
                ('project_id', models.PositiveIntegerField(verbose_name='project_id')),
                ('web_url', models.URLField(verbose_name='web url')),
                ('due_date', models.DateTimeField(verbose_name='dua date')),
                ('time_spent', models.CharField(max_length=50, verbose_name='time spent')),
            ],
            options={
                'verbose_name': ('work log',),
                'verbose_name_plural': 'work logs',
            },
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
