# Generated by Django 2.2.2 on 2019-07-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_parse', '0003_auto_20190628_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='dua date'),
        ),
    ]
